export const pricingData = [
  {
    id: 1,
    title: "TRY IT",
    name: "STARTER",
    trial: " 3 days trial",
    lookup_key: "zodiya_trial_test",
    type: "TRIAL",
    offer: [
      "Natal Chart Report",
      "Synstry chart",
      "Transit chart",
      "Solar return chart",
      "Numerology insight",
      "Daily Tarot",
    ],
    shortOffer: "Natal Chart Report ",
    price: "2.99",
    billed: "3 days trial. Then €19.99 weekly",
  },
  {
    id: 2,
    title: "HOT OFFER",
    name: "PREMIUM",
    trial: " 2 months",
    lookup_key: "zodiya_premium_test",
    type: "PREMIUM",
    offer: [
      "All included in",
      "Starter +",
      "Synstry report",
      "Transit report",
      "Solar return report",
      "Numerology report",
    ],
    discount: "-10%",
    price: "14.99",
    shortOffer: "All included in Starter  + full access on all reports",

    billed: "weekly billed for 2 months",
  },
  {
    id: 3,
    title: "SALE",
    name: "GOLD",
    trial: " 3 months",
    lookup_key: "zodiya_gold_test",
    type: "GOLD",
    offer: [
      "All included in",
      "Starter +",
      "Synstry report",
      "Transit report",
      "Solar return report",
      "Numerology report",
    ],
    discount: "-20%",
    price: "13.99",
    shortOffer: "All included in  Premium  + special offers",
    billed: "weekly billed for 3 months",
  },
];
